#!/usr/bin/env bash
# post-edit.sh — PostToolUse hook for Edit|Write.
#
# If the project defines scripts/format.sh (generated by /onboard for the
# chosen stack), run it on the file that was just edited. Formatting is
# best-effort and non-blocking: this hook ALWAYS exits 0.
set -uo pipefail

cd "${CLAUDE_PROJECT_DIR:-$PWD}" 2>/dev/null || true

fmt="scripts/format.sh"
if [ ! -f "$fmt" ] || [ ! -x "$fmt" ]; then
  exit 0
fi

input=$(cat 2>/dev/null || true)
file_path=""
if [ -n "$input" ] && command -v jq >/dev/null 2>&1; then
  file_path=$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty' 2>/dev/null) || file_path=""
fi
[ -n "$file_path" ] || exit 0
[ -f "$file_path" ] || exit 0

"$fmt" "$file_path" >/dev/null 2>&1 || true
exit 0
