#!/usr/bin/env bash
# stop-gate.sh — Stop hook.
#
# If the project defines scripts/verify-quick.sh (generated by /onboard for
# the chosen stack), run it before letting the session end. On failure, emit
# a JSON block decision so the agent keeps working until the check is green.
# If the script is absent (template mode / early project), exit silently.
# Claude Code auto-overrides after 8 consecutive blocks, so this cannot loop
# forever.
set -uo pipefail

cd "${CLAUDE_PROJECT_DIR:-$PWD}" 2>/dev/null || true

# Drain stdin (hook input JSON) — not needed here, but never leave it hanging.
cat >/dev/null 2>&1 || true

script="scripts/verify-quick.sh"
if [ ! -f "$script" ] || [ ! -x "$script" ]; then
  exit 0
fi

output=$("$script" 2>&1)
status=$?
if [ "$status" -eq 0 ]; then
  exit 0
fi

# Cap the reason at ~800 characters total; keep the tail (where errors live)
# and flatten newlines for JSON safety.
reason_tail=$(printf '%s' "$output" | tail -c 700 | tr '\n\r' '  ')
reason="verify-quick failed: $reason_tail"

if command -v jq >/dev/null 2>&1; then
  jq -cn --arg reason "$reason" '{decision: "block", reason: $reason}'
else
  escaped=$(printf '%s' "$reason" | sed 's/\\/\\\\/g; s/"/\\"/g')
  printf '{"decision":"block","reason":"%s"}\n' "$escaped"
fi
exit 0
