#!/usr/bin/env bash
#
# init.sh — environment doctor & app launcher for this template.
#
#   ./init.sh          same as ./init.sh doctor
#   ./init.sh doctor   check the local toolchain (informational, always exits 0)
#   ./init.sh start    launch the app via scripts/run.sh (generated by /onboard)
#
set -euo pipefail

MODE="${1:-doctor}"
PASS=0
FAIL=0

ok() {
  printf '  ✓ %s\n' "$1"
  PASS=$((PASS + 1))
}

ko() {
  printf '  ✗ %s\n' "$1"
  printf '      hint: %s\n' "$2"
  FAIL=$((FAIL + 1))
}

doctor() {
  printf 'Environment doctor — informational only, nothing gets installed.\n\n'

  if [ "$(uname -s)" = "Darwin" ]; then
    ok "macOS $(sw_vers -productVersion 2>/dev/null || echo '(version unknown)')"
  else
    ko "macOS not detected ($(uname -s))" \
       "native iOS builds need macOS + Xcode; web or Expo EAS cloud builds still work"
  fi

  if xcode-select -p >/dev/null 2>&1; then
    ok "Xcode developer directory: $(xcode-select -p)"
  else
    ko "Xcode command line tools missing" \
       "run: xcode-select --install (or install Xcode from the App Store) — iOS only"
  fi

  if command -v xcodebuild >/dev/null 2>&1 && xcodebuild -version >/dev/null 2>&1; then
    ok "$(xcodebuild -version 2>/dev/null | head -n 1)"
  else
    ko "xcodebuild unavailable" \
       "install Xcode, open it once and accept the license (sudo xcodebuild -license accept) — iOS only"
  fi

  if command -v xcrun >/dev/null 2>&1 && xcrun simctl list devices booted 2>/dev/null | grep -q "(Booted)"; then
    ok "iOS simulator booted: $(xcrun simctl list devices booted 2>/dev/null | grep '(Booted)' | head -n 1 | sed 's/^ *//;s/ (.*//')"
  else
    ko "no booted iOS simulator" \
       "run: open -a Simulator (the agent can also boot one via MCP) — iOS only"
  fi

  if command -v node >/dev/null 2>&1; then
    NODE_V="$(node --version 2>/dev/null | sed 's/^v//')"
    NODE_MAJOR="$(printf '%s' "$NODE_V" | cut -d. -f1)"
    case "$NODE_MAJOR" in
      ''|*[!0-9]*)
        ko "node version unreadable (got: '$NODE_V')" "install Node 18+ from https://nodejs.org" ;;
      *)
        if [ "$NODE_MAJOR" -ge 18 ]; then
          ok "node v$NODE_V (>= 18)"
        else
          ko "node v$NODE_V is too old" "MCP servers need Node 18+; install via https://nodejs.org or nvm"
        fi ;;
    esac
  else
    ko "node not found" "install Node 18+ (https://nodejs.org) — required by the MCP servers"
  fi

  if command -v jq >/dev/null 2>&1; then
    ok "jq $(jq --version 2>/dev/null | sed 's/^jq-//')"
  else
    ko "jq not found" "run: brew install jq — hooks and features.json tooling depend on it"
  fi

  if command -v git >/dev/null 2>&1; then
    ok "$(git --version 2>/dev/null)"
  else
    ko "git not found" "install the Xcode command line tools, or: brew install git"
  fi

  printf '\nSummary: %d ok, %d to fix.\n' "$PASS" "$FAIL"
  if [ "$FAIL" -gt 0 ]; then
    printf 'Failures are informational — fix only what your target platform needs.\n'
  else
    printf 'Environment looks good. Next: run `claude`, then /onboard (first time) or /build-next.\n'
  fi
}

start() {
  if [ -x "scripts/run.sh" ]; then
    exec ./scripts/run.sh
  else
    printf 'scripts/run.sh does not exist yet — it is generated by onboarding.\n'
    printf 'Run `claude` in this folder, then /onboard: the app scaffold and its run script will be created.\n'
    exit 1
  fi
}

case "$MODE" in
  doctor) doctor ;;
  start)  start ;;
  *)
    printf 'Unknown mode: %s\nUsage: ./init.sh [doctor|start]\n' "$MODE"
    exit 1 ;;
esac
